### ISSUE TITLE
Review activity : Establish and maintain a hierarchy

### ISSUE THREAD

**Issue by InduriRachana** [pothuguntaumesh/smarter-university-system#19]
This is an activity for #1 
Determine the hierarchy and assign all activities to the appropriate epic

**Comment by pothuguntaumesh** [comment]
@InduriRachana I've taken a look all the activities, and each activity is appropriately linked with the EPIC. Also, hierarchy is maintained between EPIC's and MVP's

**Comment by subhamUMD** [comment]
All activities are linked to their respective epics.

**Comment by AnirbanDey-9497** [comment]
Upon reviewing this activity it was found that the hierachy was maintained and all activities were linked to their concerned EPICS

**Comment by ZhuofanHuang** [comment]
All the activities and epics are linked as supposed.
