### ISSUE TITLE
Identify the Epics for the User Stories.

### ISSUE THREAD

**Issue by pothuguntaumesh** [pothuguntaumesh/smarter-university-system#23]
Activity for Epic #3 
Activity to add Epics for the User stories.

**Comment by pothuguntaumesh** [comment]
@subhamUMD  Now that we have discussed all the epics for User stories, please go ahead and add these in the google sheet. Please mark this activity as done after adding all the epics to the google sheet.

**Comment by subhamUMD** [comment]
@pothuguntaumesh I have added all the user stories in the google sheet.
