### ISSUE TITLE
 Review Bigraph and priority: Umesh

### ISSUE THREAD

**Issue by pothuguntaumesh** [pothuguntaumesh/smarter-university-system#27]
Activity for the Epic #4 
For the completed Bigraph, get the feedback from all other team mates.

**Comment by ZhuofanHuang** [comment]
I think 27 is more important than 16 as in the sheet, but not in the graph.

**Comment by InduriRachana** [comment]
@pothuguntaumesh according to the priorities ID 16 is less prior than 6 so it comes left to 6 but in the tree I can see 27 to the left of 6.

**Comment by pothuguntaumesh** [comment]
@InduriRachana  @ZhuofanHuang  I've corrected the bigraph, please take a look at it now and give your inputs.

**Comment by subhamUMD** [comment]
Now the graph is correct as per your priorities.

**Comment by AnirbanDey-9497** [comment]
The bigraph looks good after the corrections made
