### ISSUE TITLE
Review bigraph and priority : Rachana

### ISSUE THREAD

**Issue by InduriRachana** [pothuguntaumesh/smarter-university-system#30]
This is an activity for Epic #4 
Review the bigraph developed

**Comment by ZhuofanHuang** [comment]
I think 17 and 26, 35 and 29 priorities are reversed in the bigraph

**Comment by InduriRachana** [comment]
@ZhuofanHuang thanks for the review, corrected the tree and updated a new one

**Comment by pothuguntaumesh** [comment]
@InduriRachana Now the graph is correct!

**Comment by AnirbanDey-9497** [comment]
Looks perfect

**Comment by subhamUMD** [comment]
The bigraph diagram matches the priority mentioned in sheet.
