### ISSUE TITLE
Review bigraph and priority :  Anirban

### ISSUE THREAD

**Issue by AnirbanDey-9497** [pothuguntaumesh/smarter-university-system#37]
This activity pertains to EPIC #4

**Comment by InduriRachana** [comment]
Some of the nodes in the graph, including node 1, appear to be missing, and the dummy nodes have not been assigned properly.  The dummy nodes can be assigned using the example provided, 8 (R8 or L8), accordingly.

**Comment by ZhuofanHuang** [comment]
The priority on the top like node 1,3 in the bigraph is not consistent with the sheet.

**Comment by InduriRachana** [comment]
@AnirbanDey-9497 nodes in your graph are not named correctly, the right node is denoted as L4 instead of R34, same goes with 35

**Comment by subhamUMD** [comment]
@AnirbanDey-9497 placeholders nodes for a parent node that does not have two child nodes should follow the standard template.

**Comment by AnirbanDey-9497** [comment]
Taken all feedbacks into account and made changes to the bigraph.

**Comment by pothuguntaumesh** [comment]
Looks good now.

**Comment by InduriRachana** [comment]
Priorities and the graph matches after the changes.

**Comment by AnirbanDey-9497** [comment]
Phew! Looks perfect to everyone finally.
