### ISSUE TITLE
Review Bigraph and priority : Subham

### ISSUE THREAD

**Issue by subhamUMD** [pothuguntaumesh/smarter-university-system#40]
Activity for Epic #4 
For the given bigraph, review and give feedback.

**Comment by InduriRachana** [comment]
The binary tree matches the priorities assigned.

**Comment by ZhuofanHuang** [comment]
It is good.

**Comment by pothuguntaumesh** [comment]
@subhamUMD  I've reviewed your bigraph and everything is correct.

**Comment by AnirbanDey-9497** [comment]
The bigraph looks good to me after extensive review
