### ISSUE TITLE
Review Activity: review all the activities created for epic creating issues

### ISSUE THREAD

**Issue by ZhuofanHuang** [pothuguntaumesh/smarter-university-system#43]
Activity for #1 
Review all the activities created for epic creating issues

**Comment by pothuguntaumesh** [comment]
@ZhuofanHuang  All the activities looks good to me.

**Comment by subhamUMD** [comment]
@ZhuofanHuang All activities have been covered.

**Comment by AnirbanDey-9497** [comment]
The activities look good

**Comment by InduriRachana** [comment]
The activities written look good
