### ISSUE TITLE
Review bigraph and priority : Zhuofan Huang

### ISSUE THREAD

**Issue by ZhuofanHuang** [pothuguntaumesh/smarter-university-system#46]
Activity for #3 
Review bigraph and priority

**Comment by InduriRachana** [comment]
Depending on the priority assigned, the binary tree may need to be modified slightly.

**Comment by ZhuofanHuang** [comment]
I found some bugs and fixed them.

**Comment by pothuguntaumesh** [comment]
@ZhuofanHuang  Bigraph looks good to me after the changes.

**Comment by subhamUMD** [comment]
The final bigraph looks good to me.

**Comment by AnirbanDey-9497** [comment]
Looks good after the changes recommended by the team members
