### ISSUE TITLE
Identify where the system might crash

### ISSUE THREAD

**Issue by InduriRachana** [pothuguntaumesh/smarter-university-system#50]
This is an activity for epic #6 
Identify all the test-cases that can break the given code and note them down.

**Comment by pothuguntaumesh** [comment]
@InduriRachana  As we disscussed in the meeting, we documented all the vulnerabilities. Now lets start working on unit-test cases.

**Comment by pothuguntaumesh** [comment]
@InduriRachana Please close this issue as this activity is completed.
