### ISSUE TITLE
Combining Activity: Combine all the test-cases written by each member into one sheet.

### ISSUE THREAD

**Issue by pothuguntaumesh** [pothuguntaumesh/smarter-university-system#52]
Activity for the Epic #5 

Combine all the test-cases written by each person into one google sheet.

**Comment by pothuguntaumesh** [comment]
@InduriRachana @AnirbanDey-9497 @subhamUMD @ZhuofanHuang  Please reply here once you are done with your test-cases. I'll add all of them to a google sheet.

**Comment by InduriRachana** [comment]
Done with the test cases, let me know if something is wrong or missing

**Comment by ZhuofanHuang** [comment]
Test cases done.

**Comment by subhamUMD** [comment]
Done with the test cases.

**Comment by pothuguntaumesh** [comment]
Done adding all the test-cases to one document.
