### ISSUE TITLE
Review Activity: Review all the test-cases written 

### ISSUE THREAD

**Issue by subhamUMD** [pothuguntaumesh/smarter-university-system#59]
This is an activity for #6 
The unit cases have to be reviewed by all team members.

**Comment by InduriRachana** [comment]
reviewed the unit test cases .

**Comment by subhamUMD** [comment]
Reviewed, good to close!

**Comment by ZhuofanHuang** [comment]
Test cases are good.

**Comment by AnirbanDey-9497** [comment]
All test cases have been reviewed and it looks good

**Comment by pothuguntaumesh** [comment]
Testcases are well written.
